# Generated by Django 5.1.3 on 2024-11-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('livelo_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('neighbourhood', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('postal_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ItemThrown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('KEYBOARD', 'Keyboard'), ('SCREEN', 'Screen'), ('MOUSE', 'Mouse'), ('CPU', 'CPU'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('MOTHERBOARD', 'Motherboard'), ('POWER_SUPPLY', 'Power Supply'), ('CASE', 'Case'), ('COOLER', 'Cooler'), ('FAN', 'Fan'), ('CABLE', 'Cable'), ('BATTERY', 'Battery'), ('CELLPHONE', 'Cellphone'), ('TABLET', 'Tablet'), ('LAPTOP', 'Laptop'), ('PRINTER', 'Printer'), ('SCANNER', 'Scanner'), ('ROUTER', 'Router'), ('COMPUTER_CASE', 'Computer Case'), ('CD_DRIVE', 'CD Drive'), ('HD', 'HD'), ('CHARGER', 'Charger'), ('HEADPHONES', 'Headphones'), ('SPEAKER', 'Speaker'), ('DISK_READER', 'Disk Reader'), ('PHONE', 'Phone'), ('WEIGHT_SCALE', 'Weight Scale'), ('POWER_BANK', 'Power Bank')], max_length=50)),
                ('trash_type', models.CharField(choices=[('GREEN', 'Green'), ('WHITE', 'White'), ('BROWN', 'Brown'), ('BLUE', 'Blue'), ('NONE', 'None')], max_length=50)),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=10)),
                ('date_of_item_thrown', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upcycleproject.client')),
            ],
        ),
    ]
