# Generated by Django 5.1.3 on 2024-11-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycleproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemthrown',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware'), ('PERIPHERAL', 'Peripheral'), ('BATTERY', 'Battery'), ('MOBILE_DEVICE', 'Mobile Device'), ('CHARGER', 'Charger'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
