# Generated by Django 5.1.3 on 2024-11-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycleproject', '0002_alter_itemthrown_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemthrown',
            name='trash_type',
        ),
        migrations.AlterField(
            model_name='itemthrown',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware'), ('MOBILE_DEVICE', 'Mobile Device'), ('COMPUTER', 'Computer'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
