# Generated by Django 5.1.3 on 2024-11-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upcycleproject', '0003_remove_itemthrown_trash_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemthrown',
            name='size',
        ),
    ]
