# Generated by Django 5.1.3 on 2024-11-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycleproject', '0005_remove_itemthrown_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
