# Generated by Django 5.1.3 on 2024-11-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcycleproject', '0014_alter_itemthrown_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
